-- MySQL Script generated by MySQL Workbench
-- Sun Jun 19 20:24:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ata` (
  `idAta` INT NOT NULL,
  `Banca_idBanca` INT NOT NULL,
  `Defesa_idDefesa` INT NOT NULL,
  PRIMARY KEY (`idAta`, `Banca_idBanca`, `Defesa_idDefesa`),
  UNIQUE INDEX `idEstudante_UNIQUE` (`idAta` ASC) VISIBLE,
  INDEX `fk_Ata_Banca1_idx` (`Banca_idBanca` ASC) VISIBLE,
  INDEX `fk_Ata_Defesa1_idx` (`Defesa_idDefesa` ASC) VISIBLE,
  CONSTRAINT `fk_Ata_Banca1`
    FOREIGN KEY (`Banca_idBanca`)
    REFERENCES `mydb`.`Banca` (`idBanca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ata_Defesa1`
    FOREIGN KEY (`Defesa_idDefesa`)
    REFERENCES `mydb`.`Defesa` (`idDefesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Banca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Banca` (
  `idBanca` INT NOT NULL,
  `Usuario_idOrientador` INT NOT NULL,
  `Usuario_idConvidadoA` INT NOT NULL,
  `Usuario_idConvidadoB` INT NOT NULL,
  PRIMARY KEY (`idBanca`, `Usuario_idOrientador`, `Usuario_idConvidadoA`, `Usuario_idConvidadoB`),
  UNIQUE INDEX `idBanca_UNIQUE` (`idBanca` ASC) VISIBLE,
  INDEX `fk_Banca_Usuario1_idx` (`Usuario_idOrientador` ASC) VISIBLE,
  INDEX `fk_Banca_Usuario2_idx` (`Usuario_idConvidadoA` ASC) VISIBLE,
  INDEX `fk_Banca_Usuario3_idx` (`Usuario_idConvidadoB` ASC) VISIBLE,
  CONSTRAINT `fk_Banca_Usuario1`
    FOREIGN KEY (`Usuario_idOrientador`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Banca_Usuario2`
    FOREIGN KEY (`Usuario_idConvidadoA`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Banca_Usuario3`
    FOREIGN KEY (`Usuario_idConvidadoB`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Defesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Defesa` (
  `idDefesa` INT NOT NULL,
  `dataDefesa` DATETIME NOT NULL,
  `localDefesa` VARCHAR(255) NOT NULL,
  `tituloDefesa` VARCHAR(255) NOT NULL,
  `descricaoDefesa` VARCHAR(255) NOT NULL,
  `tags` VARCHAR(255) NOT NULL,
  `Usuario_idEstudante` INT NOT NULL,
  `Banca_idBanca` INT NOT NULL,
  PRIMARY KEY (`idDefesa`, `Usuario_idEstudante`, `Banca_idBanca`),
  UNIQUE INDEX `tituloDefesa_UNIQUE` (`tituloDefesa` ASC) VISIBLE,
  INDEX `fk_Defesa_Usuario1_idx` (`Usuario_idEstudante` ASC) VISIBLE,
  INDEX `fk_Defesa_Banca1_idx` (`Banca_idBanca` ASC) VISIBLE,
  CONSTRAINT `fk_Defesa_Usuario1`
    FOREIGN KEY (`Usuario_idEstudante`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Defesa_Banca1`
    FOREIGN KEY (`Banca_idBanca`)
    REFERENCES `mydb`.`Banca` (`idBanca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfil` (
  `idPerfil` INT NOT NULL,
  `nomePerfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil`),
  UNIQUE INDEX `nomePerfil_UNIQUE` (`nomePerfil` ASC) VISIBLE,
  UNIQUE INDEX `idPerfil_UNIQUE` (`idPerfil` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nomeUsuario` VARCHAR(255) NOT NULL,
  `statusUsuario` VARCHAR(255) NOT NULL,
  `senhaCriptografada` VARCHAR(45) NOT NULL,
  `matriculaCriptografada` VARCHAR(45) NOT NULL,
  `Assinatura` VARCHAR(255) NOT NULL,
  `Perfil_idPerfil` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Perfil_idPerfil`),
  UNIQUE INDEX `matriculaCriptografada_UNIQUE` (`matriculaCriptografada` ASC) VISIBLE,
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `Assinatura_UNIQUE` (`Assinatura` ASC) VISIBLE,
  INDEX `fk_Usuario_Perfil1_idx` (`Perfil_idPerfil` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Perfil1`
    FOREIGN KEY (`Perfil_idPerfil`)
    REFERENCES `mydb`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
